//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.09.06 at 03:31:24 PM IST 
//


package https.nosql_ladbrokes_com.v1.content.couchbaseracingcontent;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HorseRaceCourse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HorseRaceCourse"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="admissionFees" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="admissionRestrictions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="childrenFacilities" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clerkOfCourse" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clerkOfScales" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="courseKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="courseName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="countryCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="clerkOfCourseAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="directionFlag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="disabledFacilities" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="flat_description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="industryCID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="judge" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="jumpDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="locale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="location" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="directions" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="directions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                             &lt;element name="transportType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                   &lt;element name="unformattedAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="parkingDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="phone" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="starter" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="steward" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="stewardsSecretary" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="meetings" type="{https://nosql.ladbrokes.com/v1/content/CouchbaseRacingContent.xsd}courseMeetings" minOccurs="0"/&gt;
 *         &lt;element name="report" type="{https://nosql.ladbrokes.com/v1/content/CouchbaseRacingContent.xsd}reportType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HorseRaceCourse", propOrder = {
    "admissionFees",
    "admissionRestrictions",
    "childrenFacilities",
    "clerkOfCourse",
    "clerkOfScales",
    "courseKey",
    "courseName",
    "countryCode",
    "clerkOfCourseAddress",
    "directionFlag",
    "disabledFacilities",
    "flatDescription",
    "industryCID",
    "judge",
    "jumpDescription",
    "locale",
    "location",
    "parkingDescription",
    "phone",
    "starter",
    "steward",
    "stewardsSecretary",
    "meetings",
    "report"
})
public class HorseRaceCourse {

    protected String admissionFees;
    protected String admissionRestrictions;
    protected String childrenFacilities;
    protected String clerkOfCourse;
    protected String clerkOfScales;
    protected String courseKey;
    protected String courseName;
    protected String countryCode;
    protected String clerkOfCourseAddress;
    protected String directionFlag;
    protected String disabledFacilities;
    @XmlElement(name = "flat_description")
    protected String flatDescription;
    protected String industryCID;
    protected String judge;
    protected String jumpDescription;
    protected String locale;
    protected HorseRaceCourse.Location location;
    protected String parkingDescription;
    protected String phone;
    protected String starter;
    protected String steward;
    protected String stewardsSecretary;
    protected CourseMeetings meetings;
    protected ReportType report;

    /**
     * Gets the value of the admissionFees property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionFees() {
        return admissionFees;
    }

    /**
     * Sets the value of the admissionFees property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionFees(String value) {
        this.admissionFees = value;
    }

    /**
     * Gets the value of the admissionRestrictions property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdmissionRestrictions() {
        return admissionRestrictions;
    }

    /**
     * Sets the value of the admissionRestrictions property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdmissionRestrictions(String value) {
        this.admissionRestrictions = value;
    }

    /**
     * Gets the value of the childrenFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChildrenFacilities() {
        return childrenFacilities;
    }

    /**
     * Sets the value of the childrenFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChildrenFacilities(String value) {
        this.childrenFacilities = value;
    }

    /**
     * Gets the value of the clerkOfCourse property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClerkOfCourse() {
        return clerkOfCourse;
    }

    /**
     * Sets the value of the clerkOfCourse property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClerkOfCourse(String value) {
        this.clerkOfCourse = value;
    }

    /**
     * Gets the value of the clerkOfScales property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClerkOfScales() {
        return clerkOfScales;
    }

    /**
     * Sets the value of the clerkOfScales property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClerkOfScales(String value) {
        this.clerkOfScales = value;
    }

    /**
     * Gets the value of the courseKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseKey() {
        return courseKey;
    }

    /**
     * Sets the value of the courseKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseKey(String value) {
        this.courseKey = value;
    }

    /**
     * Gets the value of the courseName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * Sets the value of the courseName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCourseName(String value) {
        this.courseName = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryCode(String value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the clerkOfCourseAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClerkOfCourseAddress() {
        return clerkOfCourseAddress;
    }

    /**
     * Sets the value of the clerkOfCourseAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClerkOfCourseAddress(String value) {
        this.clerkOfCourseAddress = value;
    }

    /**
     * Gets the value of the directionFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDirectionFlag() {
        return directionFlag;
    }

    /**
     * Sets the value of the directionFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDirectionFlag(String value) {
        this.directionFlag = value;
    }

    /**
     * Gets the value of the disabledFacilities property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisabledFacilities() {
        return disabledFacilities;
    }

    /**
     * Sets the value of the disabledFacilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisabledFacilities(String value) {
        this.disabledFacilities = value;
    }

    /**
     * Gets the value of the flatDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlatDescription() {
        return flatDescription;
    }

    /**
     * Sets the value of the flatDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlatDescription(String value) {
        this.flatDescription = value;
    }

    /**
     * Gets the value of the industryCID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndustryCID() {
        return industryCID;
    }

    /**
     * Sets the value of the industryCID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndustryCID(String value) {
        this.industryCID = value;
    }

    /**
     * Gets the value of the judge property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJudge() {
        return judge;
    }

    /**
     * Sets the value of the judge property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJudge(String value) {
        this.judge = value;
    }

    /**
     * Gets the value of the jumpDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJumpDescription() {
        return jumpDescription;
    }

    /**
     * Sets the value of the jumpDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJumpDescription(String value) {
        this.jumpDescription = value;
    }

    /**
     * Gets the value of the locale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocale() {
        return locale;
    }

    /**
     * Sets the value of the locale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocale(String value) {
        this.locale = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link HorseRaceCourse.Location }
     *     
     */
    public HorseRaceCourse.Location getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link HorseRaceCourse.Location }
     *     
     */
    public void setLocation(HorseRaceCourse.Location value) {
        this.location = value;
    }

    /**
     * Gets the value of the parkingDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParkingDescription() {
        return parkingDescription;
    }

    /**
     * Sets the value of the parkingDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParkingDescription(String value) {
        this.parkingDescription = value;
    }

    /**
     * Gets the value of the phone property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPhone() {
        return phone;
    }

    /**
     * Sets the value of the phone property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPhone(String value) {
        this.phone = value;
    }

    /**
     * Gets the value of the starter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStarter() {
        return starter;
    }

    /**
     * Sets the value of the starter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStarter(String value) {
        this.starter = value;
    }

    /**
     * Gets the value of the steward property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSteward() {
        return steward;
    }

    /**
     * Sets the value of the steward property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSteward(String value) {
        this.steward = value;
    }

    /**
     * Gets the value of the stewardsSecretary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStewardsSecretary() {
        return stewardsSecretary;
    }

    /**
     * Sets the value of the stewardsSecretary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStewardsSecretary(String value) {
        this.stewardsSecretary = value;
    }

    /**
     * Gets the value of the meetings property.
     * 
     * @return
     *     possible object is
     *     {@link CourseMeetings }
     *     
     */
    public CourseMeetings getMeetings() {
        return meetings;
    }

    /**
     * Sets the value of the meetings property.
     * 
     * @param value
     *     allowed object is
     *     {@link CourseMeetings }
     *     
     */
    public void setMeetings(CourseMeetings value) {
        this.meetings = value;
    }

    /**
     * Gets the value of the report property.
     * 
     * @return
     *     possible object is
     *     {@link ReportType }
     *     
     */
    public ReportType getReport() {
        return report;
    }

    /**
     * Sets the value of the report property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReportType }
     *     
     */
    public void setReport(ReportType value) {
        this.report = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="directions" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="directions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                   &lt;element name="transportType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *         &lt;element name="unformattedAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "directions",
        "unformattedAddress"
    })
    public static class Location {

        protected List<HorseRaceCourse.Location.Directions> directions;
        protected String unformattedAddress;

        /**
         * Gets the value of the directions property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the directions property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDirections().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link HorseRaceCourse.Location.Directions }
         * 
         * 
         */
        public List<HorseRaceCourse.Location.Directions> getDirections() {
            if (directions == null) {
                directions = new ArrayList<HorseRaceCourse.Location.Directions>();
            }
            return this.directions;
        }

        /**
         * Gets the value of the unformattedAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUnformattedAddress() {
            return unformattedAddress;
        }

        /**
         * Sets the value of the unformattedAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUnformattedAddress(String value) {
            this.unformattedAddress = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="directions" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *         &lt;element name="transportType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "directions",
            "transportType"
        })
        public static class Directions {

            protected String directions;
            protected String transportType;

            /**
             * Gets the value of the directions property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDirections() {
                return directions;
            }

            /**
             * Sets the value of the directions property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDirections(String value) {
                this.directions = value;
            }

            /**
             * Gets the value of the transportType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTransportType() {
                return transportType;
            }

            /**
             * Sets the value of the transportType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTransportType(String value) {
                this.transportType = value;
            }

        }

    }

}
