//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.services.service.commonmessage._2;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the uk.co.ladbrokes.services.service.commonmessage._2 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _FindRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "FindRequest");
    private final static QName _NameValuePair_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "NameValuePair");
    private final static QName _Notify_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "Notify");
    private final static QName _ProcessResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ProcessResponse");
    private final static QName _PublishRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "PublishRequest");
    private final static QName _ServiceWarning_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceWarning");
    private final static QName _ServiceWarnings_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceWarnings");
    private final static QName _SubscribeRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SubscribeRequest");
    private final static QName _SubscribeResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SubscribeResponse");
    private final static QName _SyncRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SyncRequest");
    private final static QName _Property_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "Property");
    private final static QName _SetRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SetRequest");
    private final static QName _SearchRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SearchRequest");
    private final static QName _ApplyRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ApplyRequest");
    private final static QName _ApplyResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ApplyResponse");
    private final static QName _BusinessEvent_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "BusinessEvent");
    private final static QName _ControlParams_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ControlParams");
    private final static QName _DataFilter_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "DataFilter");
    private final static QName _DataFilters_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "DataFilters");
    private final static QName _ExtractRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ExtractRequest");
    private final static QName _ExtractResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ExtractResponse");
    private final static QName _LoadRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "LoadRequest");
    private final static QName _LoadResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "LoadResponse");
    private final static QName _SearchResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SearchResponse");
    private final static QName _SecurityDetail_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SecurityDetail");
    private final static QName _ServiceAcknowledgement_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceAcknowledgement");
    private final static QName _ServiceDetail_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceDetail");
    private final static QName _ServiceHeader_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceHeader");
    private final static QName _ServiceRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceRequest");
    private final static QName _ServiceResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceResponse");
    private final static QName _ServiceError_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ServiceError");
    private final static QName _StatusRecord_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "StatusRecord");
    private final static QName _UpdateRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "UpdateRequest");
    private final static QName _UpdateResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "UpdateResponse");
    private final static QName _UserDetail_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "UserDetail");
    private final static QName _WrapperServiceResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "WrapperServiceResponse");
    private final static QName _PublishResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "PublishResponse");
    private final static QName _RequestRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "RequestRequest");
    private final static QName _RequestResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "RequestResponse");
    private final static QName _Payload_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "Payload");
    private final static QName _ValidationDetail_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ValidationDetail");
    private final static QName _SyncResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SyncResponse");
    private final static QName _TriggerRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "TriggerRequest");
    private final static QName _TriggerResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "TriggerResponse");
    private final static QName _SetResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SetResponse");
    private final static QName _ArrayOfEnumValues_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ArrayOfEnumValues");
    private final static QName _EnumValue_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "EnumValue");
    private final static QName _ArrayOfStatusRecord_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ArrayOfStatusRecord");
    private final static QName _ClientDetail_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ClientDetail");
    private final static QName _CreateRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "CreateRequest");
    private final static QName _CreateResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "CreateResponse");
    private final static QName _DeleteRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "DeleteRequest");
    private final static QName _DeleteResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "DeleteResponse");
    private final static QName _GetRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "GetRequest");
    private final static QName _GetResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "GetResponse");
    private final static QName _ProcessRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ProcessRequest");
    private final static QName _SearchEventRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "SearchEventRequest");
    private final static QName _ActionRequest_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ActionRequest");
    private final static QName _ActionResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "ActionResponse");
    private final static QName _FindResponse_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "FindResponse");
    private final static QName _QueryFilters_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "QueryFilters");
    private final static QName _QueryFilter_QNAME = new QName("http://services.ladbrokes.co.uk/service/CommonMessage/2.0", "QueryFilter");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: uk.co.ladbrokes.services.service.commonmessage._2
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceHeader }
     * 
     */
    public ServiceHeader createServiceHeader() {
        return new ServiceHeader();
    }

    /**
     * Create an instance of {@link DataFilters }
     * 
     */
    public DataFilters createDataFilters() {
        return new DataFilters();
    }

    /**
     * Create an instance of {@link QueryFilters }
     * 
     */
    public QueryFilters createQueryFilters() {
        return new QueryFilters();
    }

    /**
     * Create an instance of {@link ControlParams }
     * 
     */
    public ControlParams createControlParams() {
        return new ControlParams();
    }

    /**
     * Create an instance of {@link ServiceError }
     * 
     */
    public ServiceError createServiceError() {
        return new ServiceError();
    }

    /**
     * Create an instance of {@link ServiceWarnings }
     * 
     */
    public ServiceWarnings createServiceWarnings() {
        return new ServiceWarnings();
    }

    /**
     * Create an instance of {@link NameValuePair }
     * 
     */
    public NameValuePair createNameValuePair() {
        return new NameValuePair();
    }

    /**
     * Create an instance of {@link ServiceWarning }
     * 
     */
    public ServiceWarning createServiceWarning() {
        return new ServiceWarning();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link BusinessEvent }
     * 
     */
    public BusinessEvent createBusinessEvent() {
        return new BusinessEvent();
    }

    /**
     * Create an instance of {@link DataFilter }
     * 
     */
    public DataFilter createDataFilter() {
        return new DataFilter();
    }

    /**
     * Create an instance of {@link SecurityDetail }
     * 
     */
    public SecurityDetail createSecurityDetail() {
        return new SecurityDetail();
    }

    /**
     * Create an instance of {@link ServiceAcknowledgement }
     * 
     */
    public ServiceAcknowledgement createServiceAcknowledgement() {
        return new ServiceAcknowledgement();
    }

    /**
     * Create an instance of {@link ServiceDetail }
     * 
     */
    public ServiceDetail createServiceDetail() {
        return new ServiceDetail();
    }

    /**
     * Create an instance of {@link StatusRecord }
     * 
     */
    public StatusRecord createStatusRecord() {
        return new StatusRecord();
    }

    /**
     * Create an instance of {@link UserDetail }
     * 
     */
    public UserDetail createUserDetail() {
        return new UserDetail();
    }

    /**
     * Create an instance of {@link WrapperServiceResponse }
     * 
     */
    public WrapperServiceResponse createWrapperServiceResponse() {
        return new WrapperServiceResponse();
    }

    /**
     * Create an instance of {@link Payload }
     * 
     */
    public Payload createPayload() {
        return new Payload();
    }

    /**
     * Create an instance of {@link ValidationDetail }
     * 
     */
    public ValidationDetail createValidationDetail() {
        return new ValidationDetail();
    }

    /**
     * Create an instance of {@link ArrayOfEnumValues }
     * 
     */
    public ArrayOfEnumValues createArrayOfEnumValues() {
        return new ArrayOfEnumValues();
    }

    /**
     * Create an instance of {@link EnumValue }
     * 
     */
    public EnumValue createEnumValue() {
        return new EnumValue();
    }

    /**
     * Create an instance of {@link ArrayOfStatusRecord }
     * 
     */
    public ArrayOfStatusRecord createArrayOfStatusRecord() {
        return new ArrayOfStatusRecord();
    }

    /**
     * Create an instance of {@link ClientDetail }
     * 
     */
    public ClientDetail createClientDetail() {
        return new ClientDetail();
    }

    /**
     * Create an instance of {@link SearchEventRequest }
     * 
     */
    public SearchEventRequest createSearchEventRequest() {
        return new SearchEventRequest();
    }

    /**
     * Create an instance of {@link QueryFilter }
     * 
     */
    public QueryFilter createQueryFilter() {
        return new QueryFilter();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "FindRequest")
    public JAXBElement<FindRequest> createFindRequest(FindRequest value) {
        return new JAXBElement<FindRequest>(_FindRequest_QNAME, FindRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameValuePair }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "NameValuePair")
    public JAXBElement<NameValuePair> createNameValuePair(NameValuePair value) {
        return new JAXBElement<NameValuePair>(_NameValuePair_QNAME, NameValuePair.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Notify }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "Notify")
    public JAXBElement<Notify> createNotify(Notify value) {
        return new JAXBElement<Notify>(_Notify_QNAME, Notify.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ProcessResponse")
    public JAXBElement<ProcessResponse> createProcessResponse(ProcessResponse value) {
        return new JAXBElement<ProcessResponse>(_ProcessResponse_QNAME, ProcessResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublishRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "PublishRequest")
    public JAXBElement<PublishRequest> createPublishRequest(PublishRequest value) {
        return new JAXBElement<PublishRequest>(_PublishRequest_QNAME, PublishRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceWarning }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceWarning")
    public JAXBElement<ServiceWarning> createServiceWarning(ServiceWarning value) {
        return new JAXBElement<ServiceWarning>(_ServiceWarning_QNAME, ServiceWarning.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceWarnings }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceWarnings")
    public JAXBElement<ServiceWarnings> createServiceWarnings(ServiceWarnings value) {
        return new JAXBElement<ServiceWarnings>(_ServiceWarnings_QNAME, ServiceWarnings.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscribeRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SubscribeRequest")
    public JAXBElement<SubscribeRequest> createSubscribeRequest(SubscribeRequest value) {
        return new JAXBElement<SubscribeRequest>(_SubscribeRequest_QNAME, SubscribeRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubscribeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SubscribeResponse")
    public JAXBElement<SubscribeResponse> createSubscribeResponse(SubscribeResponse value) {
        return new JAXBElement<SubscribeResponse>(_SubscribeResponse_QNAME, SubscribeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SyncRequest")
    public JAXBElement<SyncRequest> createSyncRequest(SyncRequest value) {
        return new JAXBElement<SyncRequest>(_SyncRequest_QNAME, SyncRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Property }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "Property")
    public JAXBElement<Property> createProperty(Property value) {
        return new JAXBElement<Property>(_Property_QNAME, Property.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SetRequest")
    public JAXBElement<SetRequest> createSetRequest(SetRequest value) {
        return new JAXBElement<SetRequest>(_SetRequest_QNAME, SetRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SearchRequest")
    public JAXBElement<SearchRequest> createSearchRequest(SearchRequest value) {
        return new JAXBElement<SearchRequest>(_SearchRequest_QNAME, SearchRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplyRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ApplyRequest")
    public JAXBElement<ApplyRequest> createApplyRequest(ApplyRequest value) {
        return new JAXBElement<ApplyRequest>(_ApplyRequest_QNAME, ApplyRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ApplyResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ApplyResponse")
    public JAXBElement<ApplyResponse> createApplyResponse(ApplyResponse value) {
        return new JAXBElement<ApplyResponse>(_ApplyResponse_QNAME, ApplyResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessEvent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "BusinessEvent")
    public JAXBElement<BusinessEvent> createBusinessEvent(BusinessEvent value) {
        return new JAXBElement<BusinessEvent>(_BusinessEvent_QNAME, BusinessEvent.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ControlParams }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ControlParams")
    public JAXBElement<ControlParams> createControlParams(ControlParams value) {
        return new JAXBElement<ControlParams>(_ControlParams_QNAME, ControlParams.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "DataFilter")
    public JAXBElement<DataFilter> createDataFilter(DataFilter value) {
        return new JAXBElement<DataFilter>(_DataFilter_QNAME, DataFilter.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DataFilters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "DataFilters")
    public JAXBElement<DataFilters> createDataFilters(DataFilters value) {
        return new JAXBElement<DataFilters>(_DataFilters_QNAME, DataFilters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtractRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ExtractRequest")
    public JAXBElement<ExtractRequest> createExtractRequest(ExtractRequest value) {
        return new JAXBElement<ExtractRequest>(_ExtractRequest_QNAME, ExtractRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExtractResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ExtractResponse")
    public JAXBElement<ExtractResponse> createExtractResponse(ExtractResponse value) {
        return new JAXBElement<ExtractResponse>(_ExtractResponse_QNAME, ExtractResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "LoadRequest")
    public JAXBElement<LoadRequest> createLoadRequest(LoadRequest value) {
        return new JAXBElement<LoadRequest>(_LoadRequest_QNAME, LoadRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoadResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "LoadResponse")
    public JAXBElement<LoadResponse> createLoadResponse(LoadResponse value) {
        return new JAXBElement<LoadResponse>(_LoadResponse_QNAME, LoadResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SearchResponse")
    public JAXBElement<SearchResponse> createSearchResponse(SearchResponse value) {
        return new JAXBElement<SearchResponse>(_SearchResponse_QNAME, SearchResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SecurityDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SecurityDetail")
    public JAXBElement<SecurityDetail> createSecurityDetail(SecurityDetail value) {
        return new JAXBElement<SecurityDetail>(_SecurityDetail_QNAME, SecurityDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceAcknowledgement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceAcknowledgement")
    public JAXBElement<ServiceAcknowledgement> createServiceAcknowledgement(ServiceAcknowledgement value) {
        return new JAXBElement<ServiceAcknowledgement>(_ServiceAcknowledgement_QNAME, ServiceAcknowledgement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceDetail")
    public JAXBElement<ServiceDetail> createServiceDetail(ServiceDetail value) {
        return new JAXBElement<ServiceDetail>(_ServiceDetail_QNAME, ServiceDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceHeader }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceHeader")
    public JAXBElement<ServiceHeader> createServiceHeader(ServiceHeader value) {
        return new JAXBElement<ServiceHeader>(_ServiceHeader_QNAME, ServiceHeader.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceRequest")
    public JAXBElement<ServiceRequest> createServiceRequest(ServiceRequest value) {
        return new JAXBElement<ServiceRequest>(_ServiceRequest_QNAME, ServiceRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceResponse")
    public JAXBElement<ServiceResponse> createServiceResponse(ServiceResponse value) {
        return new JAXBElement<ServiceResponse>(_ServiceResponse_QNAME, ServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceError }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ServiceError")
    public JAXBElement<ServiceError> createServiceError(ServiceError value) {
        return new JAXBElement<ServiceError>(_ServiceError_QNAME, ServiceError.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StatusRecord }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "StatusRecord")
    public JAXBElement<StatusRecord> createStatusRecord(StatusRecord value) {
        return new JAXBElement<StatusRecord>(_StatusRecord_QNAME, StatusRecord.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "UpdateRequest")
    public JAXBElement<UpdateRequest> createUpdateRequest(UpdateRequest value) {
        return new JAXBElement<UpdateRequest>(_UpdateRequest_QNAME, UpdateRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "UpdateResponse")
    public JAXBElement<UpdateResponse> createUpdateResponse(UpdateResponse value) {
        return new JAXBElement<UpdateResponse>(_UpdateResponse_QNAME, UpdateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UserDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "UserDetail")
    public JAXBElement<UserDetail> createUserDetail(UserDetail value) {
        return new JAXBElement<UserDetail>(_UserDetail_QNAME, UserDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WrapperServiceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "WrapperServiceResponse")
    public JAXBElement<WrapperServiceResponse> createWrapperServiceResponse(WrapperServiceResponse value) {
        return new JAXBElement<WrapperServiceResponse>(_WrapperServiceResponse_QNAME, WrapperServiceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PublishResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "PublishResponse")
    public JAXBElement<PublishResponse> createPublishResponse(PublishResponse value) {
        return new JAXBElement<PublishResponse>(_PublishResponse_QNAME, PublishResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "RequestRequest")
    public JAXBElement<RequestRequest> createRequestRequest(RequestRequest value) {
        return new JAXBElement<RequestRequest>(_RequestRequest_QNAME, RequestRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RequestResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "RequestResponse")
    public JAXBElement<RequestResponse> createRequestResponse(RequestResponse value) {
        return new JAXBElement<RequestResponse>(_RequestResponse_QNAME, RequestResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Payload }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "Payload")
    public JAXBElement<Payload> createPayload(Payload value) {
        return new JAXBElement<Payload>(_Payload_QNAME, Payload.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ValidationDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ValidationDetail")
    public JAXBElement<ValidationDetail> createValidationDetail(ValidationDetail value) {
        return new JAXBElement<ValidationDetail>(_ValidationDetail_QNAME, ValidationDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SyncResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SyncResponse")
    public JAXBElement<SyncResponse> createSyncResponse(SyncResponse value) {
        return new JAXBElement<SyncResponse>(_SyncResponse_QNAME, SyncResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "TriggerRequest")
    public JAXBElement<TriggerRequest> createTriggerRequest(TriggerRequest value) {
        return new JAXBElement<TriggerRequest>(_TriggerRequest_QNAME, TriggerRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TriggerResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "TriggerResponse")
    public JAXBElement<TriggerResponse> createTriggerResponse(TriggerResponse value) {
        return new JAXBElement<TriggerResponse>(_TriggerResponse_QNAME, TriggerResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SetResponse")
    public JAXBElement<SetResponse> createSetResponse(SetResponse value) {
        return new JAXBElement<SetResponse>(_SetResponse_QNAME, SetResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfEnumValues }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ArrayOfEnumValues")
    public JAXBElement<ArrayOfEnumValues> createArrayOfEnumValues(ArrayOfEnumValues value) {
        return new JAXBElement<ArrayOfEnumValues>(_ArrayOfEnumValues_QNAME, ArrayOfEnumValues.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EnumValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "EnumValue")
    public JAXBElement<EnumValue> createEnumValue(EnumValue value) {
        return new JAXBElement<EnumValue>(_EnumValue_QNAME, EnumValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ArrayOfStatusRecord }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ArrayOfStatusRecord")
    public JAXBElement<ArrayOfStatusRecord> createArrayOfStatusRecord(ArrayOfStatusRecord value) {
        return new JAXBElement<ArrayOfStatusRecord>(_ArrayOfStatusRecord_QNAME, ArrayOfStatusRecord.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ClientDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ClientDetail")
    public JAXBElement<ClientDetail> createClientDetail(ClientDetail value) {
        return new JAXBElement<ClientDetail>(_ClientDetail_QNAME, ClientDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "CreateRequest")
    public JAXBElement<CreateRequest> createCreateRequest(CreateRequest value) {
        return new JAXBElement<CreateRequest>(_CreateRequest_QNAME, CreateRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "CreateResponse")
    public JAXBElement<CreateResponse> createCreateResponse(CreateResponse value) {
        return new JAXBElement<CreateResponse>(_CreateResponse_QNAME, CreateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "DeleteRequest")
    public JAXBElement<DeleteRequest> createDeleteRequest(DeleteRequest value) {
        return new JAXBElement<DeleteRequest>(_DeleteRequest_QNAME, DeleteRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DeleteResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "DeleteResponse")
    public JAXBElement<DeleteResponse> createDeleteResponse(DeleteResponse value) {
        return new JAXBElement<DeleteResponse>(_DeleteResponse_QNAME, DeleteResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "GetRequest")
    public JAXBElement<GetRequest> createGetRequest(GetRequest value) {
        return new JAXBElement<GetRequest>(_GetRequest_QNAME, GetRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "GetResponse")
    public JAXBElement<GetResponse> createGetResponse(GetResponse value) {
        return new JAXBElement<GetResponse>(_GetResponse_QNAME, GetResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ProcessRequest")
    public JAXBElement<ProcessRequest> createProcessRequest(ProcessRequest value) {
        return new JAXBElement<ProcessRequest>(_ProcessRequest_QNAME, ProcessRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SearchEventRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "SearchEventRequest")
    public JAXBElement<SearchEventRequest> createSearchEventRequest(SearchEventRequest value) {
        return new JAXBElement<SearchEventRequest>(_SearchEventRequest_QNAME, SearchEventRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionRequest }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ActionRequest")
    public JAXBElement<ActionRequest> createActionRequest(ActionRequest value) {
        return new JAXBElement<ActionRequest>(_ActionRequest_QNAME, ActionRequest.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ActionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "ActionResponse")
    public JAXBElement<ActionResponse> createActionResponse(ActionResponse value) {
        return new JAXBElement<ActionResponse>(_ActionResponse_QNAME, ActionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FindResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "FindResponse")
    public JAXBElement<FindResponse> createFindResponse(FindResponse value) {
        return new JAXBElement<FindResponse>(_FindResponse_QNAME, FindResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryFilters }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "QueryFilters")
    public JAXBElement<QueryFilters> createQueryFilters(QueryFilters value) {
        return new JAXBElement<QueryFilters>(_QueryFilters_QNAME, QueryFilters.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QueryFilter }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://services.ladbrokes.co.uk/service/CommonMessage/2.0", name = "QueryFilter")
    public JAXBElement<QueryFilter> createQueryFilter(QueryFilter value) {
        return new JAXBElement<QueryFilter>(_QueryFilter_QNAME, QueryFilter.class, null, value);
    }

}
