//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.customer.customer._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CustomerKeyTypeKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CustomerKeyTypeKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SystemKey"/&gt;
 *     &lt;enumeration value="Email"/&gt;
 *     &lt;enumeration value="UserName"/&gt;
 *     &lt;enumeration value="SocialMediaUser"/&gt;
 *     &lt;enumeration value="Token"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CustomerKeyTypeKind")
@XmlEnum
public enum CustomerKeyTypeKind {


    /**
     * A general unique system level Key.  e.g. custId=1232342
     * 
     */
    @XmlEnumValue("SystemKey")
    SYSTEM_KEY("SystemKey"),

    /**
     * An email identifier e.g. kdmaile@yahoo.com
     * 
     */
    @XmlEnumValue("Email")
    EMAIL("Email"),

    /**
     * A user defined user name understood by a system (e.g. Ladbrokes online userName)
     * 
     */
    @XmlEnumValue("UserName")
    USER_NAME("UserName"),

    /**
     * A social media user name for Twitter and Facebook
     * 
     */
    @XmlEnumValue("SocialMediaUser")
    SOCIAL_MEDIA_USER("SocialMediaUser"),

    /**
     * A token, that has the lifespan of a period of time, that can be used to identify a customer (e.g. session token from openBet, oAuth token from facebook connect, SAML token)
     * 
     */
    @XmlEnumValue("Token")
    TOKEN("Token"),

    /**
     * TBD - Other - Future extension?
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    CustomerKeyTypeKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CustomerKeyTypeKind fromValue(String v) {
        for (CustomerKeyTypeKind c: CustomerKeyTypeKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
