//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.customer.customer._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * This class represents unique identification for a customer.  A customer can be identified in a number of different systems in Ladbrokes.  This class represents a single identification key - there may (most likely is) a number of these for each system.
 * 
 * MDM programme would resolve this down to 1, the MDM unique key
 * 
 * <p>Java class for CustomerKey complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomerKey"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="key" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="system" type="{http://cdm.ladbrokes.co.uk/customer/Customer/2.0}SystemKind" minOccurs="0"/&gt;
 *         &lt;element name="type" type="{http://cdm.ladbrokes.co.uk/customer/Customer/2.0}CustomerKeyTypeKind" minOccurs="0"/&gt;
 *         &lt;element name="sessionToken" type="{http://cdm.ladbrokes.co.uk/customer/Customer/2.0}SessionToken" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomerKey", propOrder = {
    "key",
    "system",
    "type",
    "sessionToken"
})
public class CustomerKey {

    protected String key;
    @XmlSchemaType(name = "string")
    protected SystemKind system;
    @XmlSchemaType(name = "string")
    protected CustomerKeyTypeKind type;
    protected SessionToken sessionToken;

    /**
     * Gets the value of the key property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKey() {
        return key;
    }

    /**
     * Sets the value of the key property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKey(String value) {
        this.key = value;
    }

    /**
     * Gets the value of the system property.
     * 
     * @return
     *     possible object is
     *     {@link SystemKind }
     *     
     */
    public SystemKind getSystem() {
        return system;
    }

    /**
     * Sets the value of the system property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemKind }
     *     
     */
    public void setSystem(SystemKind value) {
        this.system = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerKeyTypeKind }
     *     
     */
    public CustomerKeyTypeKind getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerKeyTypeKind }
     *     
     */
    public void setType(CustomerKeyTypeKind value) {
        this.type = value;
    }

    /**
     * Gets the value of the sessionToken property.
     * 
     * @return
     *     possible object is
     *     {@link SessionToken }
     *     
     */
    public SessionToken getSessionToken() {
        return sessionToken;
    }

    /**
     * Sets the value of the sessionToken property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionToken }
     *     
     */
    public void setSessionToken(SessionToken value) {
        this.sessionToken = value;
    }

}
