//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.customer.transaction._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import uk.co.ladbrokes.cdm.banking.payment._2.Payment;
import uk.co.ladbrokes.cdm.banking.wallet._2.WalletTransaction;
import uk.co.ladbrokes.cdm.common.managedentity._2.ManagedEntity;


/**
 * An Abstract Transaction class which all transactions inherit from
 * 
 * <p>Java class for Transaction complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Transaction"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cdm.ladbrokes.co.uk/common/ManagedEntity/2.0}ManagedEntity"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="transactionKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="accountKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="transactionType" type="{http://cdm.ladbrokes.co.uk/customer/Transaction/2.0}TransactionType" minOccurs="0"/&gt;
 *         &lt;element name="transactionSubtype" type="{http://cdm.ladbrokes.co.uk/customer/Transaction/2.0}TransactionSubtype" minOccurs="0"/&gt;
 *         &lt;element name="requestedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="completedDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="transactionCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="transactionCharacteristics" type="{http://cdm.ladbrokes.co.uk/customer/Transaction/2.0}TransactionCharacteristics" minOccurs="0"/&gt;
 *         &lt;element name="transactionSource" type="{http://cdm.ladbrokes.co.uk/customer/Transaction/2.0}TransactionSource" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Transaction", propOrder = {
    "transactionKey",
    "accountKey",
    "transactionType",
    "transactionSubtype",
    "requestedDateTime",
    "completedDateTime",
    "transactionCode",
    "transactionCharacteristics",
    "transactionSource"
})
@XmlSeeAlso({
    WalletTransaction.class,
    Payment.class,
    LoyaltyTransaction.class
})
public abstract class Transaction
    extends ManagedEntity
{

    protected String transactionKey;
    protected String accountKey;
    protected TransactionType transactionType;
    protected TransactionSubtype transactionSubtype;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar requestedDateTime;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar completedDateTime;
    protected String transactionCode;
    protected TransactionCharacteristics transactionCharacteristics;
    protected TransactionSource transactionSource;

    /**
     * Gets the value of the transactionKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionKey() {
        return transactionKey;
    }

    /**
     * Sets the value of the transactionKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionKey(String value) {
        this.transactionKey = value;
    }

    /**
     * Gets the value of the accountKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountKey() {
        return accountKey;
    }

    /**
     * Sets the value of the accountKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountKey(String value) {
        this.accountKey = value;
    }

    /**
     * Gets the value of the transactionType property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionType }
     *     
     */
    public TransactionType getTransactionType() {
        return transactionType;
    }

    /**
     * Sets the value of the transactionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionType }
     *     
     */
    public void setTransactionType(TransactionType value) {
        this.transactionType = value;
    }

    /**
     * Gets the value of the transactionSubtype property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionSubtype }
     *     
     */
    public TransactionSubtype getTransactionSubtype() {
        return transactionSubtype;
    }

    /**
     * Sets the value of the transactionSubtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionSubtype }
     *     
     */
    public void setTransactionSubtype(TransactionSubtype value) {
        this.transactionSubtype = value;
    }

    /**
     * Gets the value of the requestedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRequestedDateTime() {
        return requestedDateTime;
    }

    /**
     * Sets the value of the requestedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRequestedDateTime(XMLGregorianCalendar value) {
        this.requestedDateTime = value;
    }

    /**
     * Gets the value of the completedDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCompletedDateTime() {
        return completedDateTime;
    }

    /**
     * Sets the value of the completedDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCompletedDateTime(XMLGregorianCalendar value) {
        this.completedDateTime = value;
    }

    /**
     * Gets the value of the transactionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransactionCode() {
        return transactionCode;
    }

    /**
     * Sets the value of the transactionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransactionCode(String value) {
        this.transactionCode = value;
    }

    /**
     * Gets the value of the transactionCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionCharacteristics }
     *     
     */
    public TransactionCharacteristics getTransactionCharacteristics() {
        return transactionCharacteristics;
    }

    /**
     * Sets the value of the transactionCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionCharacteristics }
     *     
     */
    public void setTransactionCharacteristics(TransactionCharacteristics value) {
        this.transactionCharacteristics = value;
    }

    /**
     * Gets the value of the transactionSource property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionSource }
     *     
     */
    public TransactionSource getTransactionSource() {
        return transactionSource;
    }

    /**
     * Sets the value of the transactionSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionSource }
     *     
     */
    public void setTransactionSource(TransactionSource value) {
        this.transactionSource = value;
    }

}
