//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.market._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import uk.co.ladbrokes.cdm.common.basetype._2.Money;


/**
 * Maintains all the rule 4 details for a market.
 * 
 * <p>Java class for MarketRule4Detail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketRule4Detail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="marketRule4Id" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="rule4Warning" type="{http://cdm.ladbrokes.co.uk/trading/Market/2.0}MarketEachWayKind" minOccurs="0"/&gt;
 *         &lt;element name="rule4PriceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="rule4Valid" type="{http://cdm.ladbrokes.co.uk/trading/Market/2.0}MarketRule4ValidKind" minOccurs="0"/&gt;
 *         &lt;element name="rule4Deduction" type="{http://cdm.ladbrokes.co.uk/common/BaseType/2.0}Money" minOccurs="0"/&gt;
 *         &lt;element name="rule4Reason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketRule4Detail", propOrder = {
    "validFrom",
    "validTo",
    "isActive",
    "marketRule4Id",
    "rule4Warning",
    "rule4PriceType",
    "rule4Valid",
    "rule4Deduction",
    "rule4Reason"
})
public class MarketRule4Detail {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFrom;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validTo;
    protected Boolean isActive;
    protected BigInteger marketRule4Id;
    @XmlSchemaType(name = "string")
    protected MarketEachWayKind rule4Warning;
    protected String rule4PriceType;
    @XmlSchemaType(name = "string")
    protected MarketRule4ValidKind rule4Valid;
    protected Money rule4Deduction;
    protected String rule4Reason;

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsActive(Boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the marketRule4Id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMarketRule4Id() {
        return marketRule4Id;
    }

    /**
     * Sets the value of the marketRule4Id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMarketRule4Id(BigInteger value) {
        this.marketRule4Id = value;
    }

    /**
     * Gets the value of the rule4Warning property.
     * 
     * @return
     *     possible object is
     *     {@link MarketEachWayKind }
     *     
     */
    public MarketEachWayKind getRule4Warning() {
        return rule4Warning;
    }

    /**
     * Sets the value of the rule4Warning property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketEachWayKind }
     *     
     */
    public void setRule4Warning(MarketEachWayKind value) {
        this.rule4Warning = value;
    }

    /**
     * Gets the value of the rule4PriceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRule4PriceType() {
        return rule4PriceType;
    }

    /**
     * Sets the value of the rule4PriceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRule4PriceType(String value) {
        this.rule4PriceType = value;
    }

    /**
     * Gets the value of the rule4Valid property.
     * 
     * @return
     *     possible object is
     *     {@link MarketRule4ValidKind }
     *     
     */
    public MarketRule4ValidKind getRule4Valid() {
        return rule4Valid;
    }

    /**
     * Sets the value of the rule4Valid property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketRule4ValidKind }
     *     
     */
    public void setRule4Valid(MarketRule4ValidKind value) {
        this.rule4Valid = value;
    }

    /**
     * Gets the value of the rule4Deduction property.
     * 
     * @return
     *     possible object is
     *     {@link Money }
     *     
     */
    public Money getRule4Deduction() {
        return rule4Deduction;
    }

    /**
     * Sets the value of the rule4Deduction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Money }
     *     
     */
    public void setRule4Deduction(Money value) {
        this.rule4Deduction = value;
    }

    /**
     * Gets the value of the rule4Reason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRule4Reason() {
        return rule4Reason;
    }

    /**
     * Sets the value of the rule4Reason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRule4Reason(String value) {
        this.rule4Reason = value;
    }

}
