//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.market._2;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Maintains Eachway details for a market. there could be multiple each way factors for a market, but latest eachway factor would active.
 * 
 * <p>Java class for MarketEachWayDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketEachWayDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="validFrom" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="validTo" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="eachWayFactor" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="eachWayNum" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="eachWayDen" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="eachWay" type="{http://cdm.ladbrokes.co.uk/trading/Market/2.0}MarketEachWayKind" minOccurs="0"/&gt;
 *         &lt;element name="eachWayPlace" type="{http://cdm.ladbrokes.co.uk/trading/Market/2.0}MarketEachWayKind" minOccurs="0"/&gt;
 *         &lt;element name="eachWayPlaces" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="eachWayAt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="eachWayTerms" type="{http://cdm.ladbrokes.co.uk/trading/Market/2.0}MarketEachWayTermsKind" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketEachWayDetail", propOrder = {
    "validFrom",
    "validTo",
    "isActive",
    "eachWayFactor",
    "eachWayNum",
    "eachWayDen",
    "eachWay",
    "eachWayPlace",
    "eachWayPlaces",
    "eachWayAt",
    "eachWayTerms"
})
public class MarketEachWayDetail {

    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validFrom;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar validTo;
    protected Boolean isActive;
    protected BigDecimal eachWayFactor;
    protected BigInteger eachWayNum;
    protected BigInteger eachWayDen;
    @XmlSchemaType(name = "string")
    protected MarketEachWayKind eachWay;
    @XmlSchemaType(name = "string")
    protected MarketEachWayKind eachWayPlace;
    protected BigInteger eachWayPlaces;
    protected String eachWayAt;
    @XmlSchemaType(name = "string")
    protected MarketEachWayTermsKind eachWayTerms;

    /**
     * Gets the value of the validFrom property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidFrom() {
        return validFrom;
    }

    /**
     * Sets the value of the validFrom property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidFrom(XMLGregorianCalendar value) {
        this.validFrom = value;
    }

    /**
     * Gets the value of the validTo property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getValidTo() {
        return validTo;
    }

    /**
     * Sets the value of the validTo property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setValidTo(XMLGregorianCalendar value) {
        this.validTo = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsActive(Boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the eachWayFactor property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getEachWayFactor() {
        return eachWayFactor;
    }

    /**
     * Sets the value of the eachWayFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setEachWayFactor(BigDecimal value) {
        this.eachWayFactor = value;
    }

    /**
     * Gets the value of the eachWayNum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEachWayNum() {
        return eachWayNum;
    }

    /**
     * Sets the value of the eachWayNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEachWayNum(BigInteger value) {
        this.eachWayNum = value;
    }

    /**
     * Gets the value of the eachWayDen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEachWayDen() {
        return eachWayDen;
    }

    /**
     * Sets the value of the eachWayDen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEachWayDen(BigInteger value) {
        this.eachWayDen = value;
    }

    /**
     * Gets the value of the eachWay property.
     * 
     * @return
     *     possible object is
     *     {@link MarketEachWayKind }
     *     
     */
    public MarketEachWayKind getEachWay() {
        return eachWay;
    }

    /**
     * Sets the value of the eachWay property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketEachWayKind }
     *     
     */
    public void setEachWay(MarketEachWayKind value) {
        this.eachWay = value;
    }

    /**
     * Gets the value of the eachWayPlace property.
     * 
     * @return
     *     possible object is
     *     {@link MarketEachWayKind }
     *     
     */
    public MarketEachWayKind getEachWayPlace() {
        return eachWayPlace;
    }

    /**
     * Sets the value of the eachWayPlace property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketEachWayKind }
     *     
     */
    public void setEachWayPlace(MarketEachWayKind value) {
        this.eachWayPlace = value;
    }

    /**
     * Gets the value of the eachWayPlaces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEachWayPlaces() {
        return eachWayPlaces;
    }

    /**
     * Sets the value of the eachWayPlaces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEachWayPlaces(BigInteger value) {
        this.eachWayPlaces = value;
    }

    /**
     * Gets the value of the eachWayAt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEachWayAt() {
        return eachWayAt;
    }

    /**
     * Sets the value of the eachWayAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEachWayAt(String value) {
        this.eachWayAt = value;
    }

    /**
     * Gets the value of the eachWayTerms property.
     * 
     * @return
     *     possible object is
     *     {@link MarketEachWayTermsKind }
     *     
     */
    public MarketEachWayTermsKind getEachWayTerms() {
        return eachWayTerms;
    }

    /**
     * Sets the value of the eachWayTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketEachWayTermsKind }
     *     
     */
    public void setEachWayTerms(MarketEachWayTermsKind value) {
        this.eachWayTerms = value;
    }

}
