//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.market._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * Maintains details of Accumulator details of the market.
 * 
 * <p>Java class for MarketAccumulatorConfig complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MarketAccumulatorConfig"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="minAccumulator" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="maxAccumulator" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="accumulatorCriteria" type="{http://cdm.ladbrokes.co.uk/trading/Market/2.0}AccumulatorCriteriaKind" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MarketAccumulatorConfig", propOrder = {
    "minAccumulator",
    "maxAccumulator",
    "accumulatorCriteria"
})
public class MarketAccumulatorConfig {

    protected BigInteger minAccumulator;
    protected BigInteger maxAccumulator;
    @XmlSchemaType(name = "string")
    protected AccumulatorCriteriaKind accumulatorCriteria;

    /**
     * Gets the value of the minAccumulator property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMinAccumulator() {
        return minAccumulator;
    }

    /**
     * Sets the value of the minAccumulator property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMinAccumulator(BigInteger value) {
        this.minAccumulator = value;
    }

    /**
     * Gets the value of the maxAccumulator property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxAccumulator() {
        return maxAccumulator;
    }

    /**
     * Sets the value of the maxAccumulator property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxAccumulator(BigInteger value) {
        this.maxAccumulator = value;
    }

    /**
     * Gets the value of the accumulatorCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link AccumulatorCriteriaKind }
     *     
     */
    public AccumulatorCriteriaKind getAccumulatorCriteria() {
        return accumulatorCriteria;
    }

    /**
     * Sets the value of the accumulatorCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link AccumulatorCriteriaKind }
     *     
     */
    public void setAccumulatorCriteria(AccumulatorCriteriaKind value) {
        this.accumulatorCriteria = value;
    }

}
