//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.market._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WebsiteLayoutStyleKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WebsiteLayoutStyleKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Default"/&gt;
 *     &lt;enumeration value="EventCoupon"/&gt;
 *     &lt;enumeration value="Coupon"/&gt;
 *     &lt;enumeration value="WinDrawWin"/&gt;
 *     &lt;enumeration value="RacingSpecials"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "WebsiteLayoutStyleKind")
@XmlEnum
public enum WebsiteLayoutStyleKind {

    @XmlEnumValue("Default")
    DEFAULT("Default"),
    @XmlEnumValue("EventCoupon")
    EVENT_COUPON("EventCoupon"),
    @XmlEnumValue("Coupon")
    COUPON("Coupon"),
    @XmlEnumValue("WinDrawWin")
    WIN_DRAW_WIN("WinDrawWin"),
    @XmlEnumValue("RacingSpecials")
    RACING_SPECIALS("RacingSpecials");
    private final String value;

    WebsiteLayoutStyleKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WebsiteLayoutStyleKind fromValue(String v) {
        for (WebsiteLayoutStyleKind c: WebsiteLayoutStyleKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
