//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.party.partyrole._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ContactPurposeKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ContactPurposeKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="General"/&gt;
 *     &lt;enumeration value="CustomerCare"/&gt;
 *     &lt;enumeration value="Payment"/&gt;
 *     &lt;enumeration value="LadbrokesPromotional"/&gt;
 *     &lt;enumeration value="PartnerPromotional"/&gt;
 *     &lt;enumeration value="Verification"/&gt;
 *     &lt;enumeration value="Fraud"/&gt;
 *     &lt;enumeration value="Any"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ContactPurposeKind")
@XmlEnum
public enum ContactPurposeKind {


    /**
     * This value indicates that the purpose of contact, by the contact method, is for general Ladbrokes informational (non marketing) reasons
     * 
     */
    @XmlEnumValue("General")
    GENERAL("General"),

    /**
     * This value indicates that the purpose of contact, by the contact method, is for Ladbrokes customer care reasons
     * 
     */
    @XmlEnumValue("CustomerCare")
    CUSTOMER_CARE("CustomerCare"),

    /**
     * This value indicates that the purpose of contact, by the contact method, is for Ladbrokes for reasons related to Payments
     * 
     */
    @XmlEnumValue("Payment")
    PAYMENT("Payment"),

    /**
     * This value indicates that the purpose of contact, by the contact method, is for Ladbrokes for promotional reasons
     * 
     */
    @XmlEnumValue("LadbrokesPromotional")
    LADBROKES_PROMOTIONAL("LadbrokesPromotional"),

    /**
     * This value indicates that the purpose of contact, by the contact method, is for Ladbrokes Partners for promotional reasons
     * 
     */
    @XmlEnumValue("PartnerPromotional")
    PARTNER_PROMOTIONAL("PartnerPromotional"),

    /**
     * This value indicates that the purpose of contact, by the contact method, is for Ladbrokes for Age or Identify verification reasons
     * 
     */
    @XmlEnumValue("Verification")
    VERIFICATION("Verification"),

    /**
     * This value indicates that the purpose of contact, by the contact method, is for Ladbrokes for Fraud reasons
     * 
     */
    @XmlEnumValue("Fraud")
    FRAUD("Fraud"),

    /**
     * This value indicates that the purpose of contact, by the contact method, is for Ladbrokes for any/all reasons
     * 
     */
    @XmlEnumValue("Any")
    ANY("Any"),

    /**
     * Placeholder for other
     * 
     */
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ContactPurposeKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ContactPurposeKind fromValue(String v) {
        for (ContactPurposeKind c: ContactPurposeKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
