//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.party.partyrole._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.common.location._2.Address;


/**
 * This class represents a method of contact for communicating with a PartyRole (e.g. Customer).  
 * 
 * A Party may have a different contact methods depending on what the role and what contact is for.
 * 
 * <p>Java class for ContactMethod complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ContactMethod"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="contactMethodKind" type="{http://cdm.ladbrokes.co.uk/party/PartyRole/2.0}ContactMethodKind" minOccurs="0"/&gt;
 *         &lt;element name="emailAddress" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="telephoneNumber" type="{http://cdm.ladbrokes.co.uk/party/PartyRole/2.0}TelephoneNumber" minOccurs="0"/&gt;
 *         &lt;element name="partyAddress" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="otherAddress" type="{http://cdm.ladbrokes.co.uk/common/Location/2.0}Address" minOccurs="0"/&gt;
 *         &lt;element name="canUse" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="contactPurpose" type="{http://cdm.ladbrokes.co.uk/party/PartyRole/2.0}ContactPurpose" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ContactMethod", propOrder = {
    "contactMethodKind",
    "emailAddress",
    "telephoneNumber",
    "partyAddress",
    "otherAddress",
    "canUse",
    "contactPurpose"
})
public class ContactMethod {

    @XmlSchemaType(name = "string")
    protected ContactMethodKind contactMethodKind;
    protected String emailAddress;
    protected TelephoneNumber telephoneNumber;
    protected Boolean partyAddress;
    protected Address otherAddress;
    protected Boolean canUse;
    protected List<ContactPurpose> contactPurpose;

    /**
     * Gets the value of the contactMethodKind property.
     * 
     * @return
     *     possible object is
     *     {@link ContactMethodKind }
     *     
     */
    public ContactMethodKind getContactMethodKind() {
        return contactMethodKind;
    }

    /**
     * Sets the value of the contactMethodKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactMethodKind }
     *     
     */
    public void setContactMethodKind(ContactMethodKind value) {
        this.contactMethodKind = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the telephoneNumber property.
     * 
     * @return
     *     possible object is
     *     {@link TelephoneNumber }
     *     
     */
    public TelephoneNumber getTelephoneNumber() {
        return telephoneNumber;
    }

    /**
     * Sets the value of the telephoneNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link TelephoneNumber }
     *     
     */
    public void setTelephoneNumber(TelephoneNumber value) {
        this.telephoneNumber = value;
    }

    /**
     * Gets the value of the partyAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPartyAddress() {
        return partyAddress;
    }

    /**
     * Sets the value of the partyAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPartyAddress(Boolean value) {
        this.partyAddress = value;
    }

    /**
     * Gets the value of the otherAddress property.
     * 
     * @return
     *     possible object is
     *     {@link Address }
     *     
     */
    public Address getOtherAddress() {
        return otherAddress;
    }

    /**
     * Sets the value of the otherAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link Address }
     *     
     */
    public void setOtherAddress(Address value) {
        this.otherAddress = value;
    }

    /**
     * Gets the value of the canUse property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanUse() {
        return canUse;
    }

    /**
     * Sets the value of the canUse property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanUse(Boolean value) {
        this.canUse = value;
    }

    /**
     * Gets the value of the contactPurpose property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the contactPurpose property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContactPurpose().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContactPurpose }
     * 
     * 
     */
    public List<ContactPurpose> getContactPurpose() {
        if (contactPurpose == null) {
            contactPurpose = new ArrayList<ContactPurpose>();
        }
        return this.contactPurpose;
    }

}
