//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.product.sportsbook._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.common.country._2.CountryCodeKind;
import uk.co.ladbrokes.cdm.common.crossref._2.CrossRefEntityKeys;


/**
 * <p>Java class for SportsbookTeam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SportsbookTeam"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="teamKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="teamName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="teamShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="teamType" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}TeamTypeKind" minOccurs="0"/&gt;
 *         &lt;element name="teamStatus" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}TeamStatusKind" minOccurs="0"/&gt;
 *         &lt;element name="countryCode" type="{http://cdm.ladbrokes.co.uk/common/Country/2.0}CountryCodeKind" minOccurs="0"/&gt;
 *         &lt;element name="teamCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="externalKeys" type="{http://cdm.ladbrokes.co.uk/common/CrossRef/2.0}CrossRefEntityKeys" minOccurs="0"/&gt;
 *         &lt;element name="sportsbookPlayer" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}SportsbookPlayer" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SportsbookTeam", propOrder = {
    "teamKey",
    "teamName",
    "teamShortName",
    "teamType",
    "teamStatus",
    "countryCode",
    "teamCategory",
    "externalKeys",
    "sportsbookPlayer"
})
public class SportsbookTeam {

    protected String teamKey;
    protected String teamName;
    protected String teamShortName;
    @XmlSchemaType(name = "string")
    protected TeamTypeKind teamType;
    @XmlSchemaType(name = "string")
    protected TeamStatusKind teamStatus;
    @XmlSchemaType(name = "string")
    protected CountryCodeKind countryCode;
    protected String teamCategory;
    protected CrossRefEntityKeys externalKeys;
    protected List<SportsbookPlayer> sportsbookPlayer;

    /**
     * Gets the value of the teamKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamKey() {
        return teamKey;
    }

    /**
     * Sets the value of the teamKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamKey(String value) {
        this.teamKey = value;
    }

    /**
     * Gets the value of the teamName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamName() {
        return teamName;
    }

    /**
     * Sets the value of the teamName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamName(String value) {
        this.teamName = value;
    }

    /**
     * Gets the value of the teamShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamShortName() {
        return teamShortName;
    }

    /**
     * Sets the value of the teamShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamShortName(String value) {
        this.teamShortName = value;
    }

    /**
     * Gets the value of the teamType property.
     * 
     * @return
     *     possible object is
     *     {@link TeamTypeKind }
     *     
     */
    public TeamTypeKind getTeamType() {
        return teamType;
    }

    /**
     * Sets the value of the teamType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamTypeKind }
     *     
     */
    public void setTeamType(TeamTypeKind value) {
        this.teamType = value;
    }

    /**
     * Gets the value of the teamStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TeamStatusKind }
     *     
     */
    public TeamStatusKind getTeamStatus() {
        return teamStatus;
    }

    /**
     * Sets the value of the teamStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TeamStatusKind }
     *     
     */
    public void setTeamStatus(TeamStatusKind value) {
        this.teamStatus = value;
    }

    /**
     * Gets the value of the countryCode property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeKind }
     *     
     */
    public CountryCodeKind getCountryCode() {
        return countryCode;
    }

    /**
     * Sets the value of the countryCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeKind }
     *     
     */
    public void setCountryCode(CountryCodeKind value) {
        this.countryCode = value;
    }

    /**
     * Gets the value of the teamCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTeamCategory() {
        return teamCategory;
    }

    /**
     * Sets the value of the teamCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTeamCategory(String value) {
        this.teamCategory = value;
    }

    /**
     * Gets the value of the externalKeys property.
     * 
     * @return
     *     possible object is
     *     {@link CrossRefEntityKeys }
     *     
     */
    public CrossRefEntityKeys getExternalKeys() {
        return externalKeys;
    }

    /**
     * Sets the value of the externalKeys property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossRefEntityKeys }
     *     
     */
    public void setExternalKeys(CrossRefEntityKeys value) {
        this.externalKeys = value;
    }

    /**
     * Gets the value of the sportsbookPlayer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sportsbookPlayer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSportsbookPlayer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SportsbookPlayer }
     * 
     * 
     */
    public List<SportsbookPlayer> getSportsbookPlayer() {
        if (sportsbookPlayer == null) {
            sportsbookPlayer = new ArrayList<SportsbookPlayer>();
        }
        return this.sportsbookPlayer;
    }

}
