//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.product.sportsbook._2;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.common.basetype._2.CurrencyCodeKind;


/**
 * This class represents a pool TBD
 * 
 * <p>Java class for SportsbookPool complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SportsbookPool"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}SportsbookCategory"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="poolKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="currency" type="{http://cdm.ladbrokes.co.uk/common/BaseType/2.0}CurrencyCodeKind" minOccurs="0"/&gt;
 *         &lt;element name="numLegs" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="poolValue" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="isActive" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="isResulted" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="poolProvider" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}PoolProvider" minOccurs="0"/&gt;
 *         &lt;element name="poolMarket" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}SportsbookMarket" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="poolType" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}PoolType" minOccurs="0"/&gt;
 *         &lt;element name="poolResult" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}PoolResult" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SportsbookPool", propOrder = {
    "poolKey",
    "currency",
    "numLegs",
    "poolValue",
    "isActive",
    "isResulted",
    "poolProvider",
    "poolMarket",
    "poolType",
    "poolResult"
})
public class SportsbookPool
    extends SportsbookCategory
{

    protected String poolKey;
    @XmlSchemaType(name = "string")
    protected CurrencyCodeKind currency;
    protected BigInteger numLegs;
    protected BigDecimal poolValue;
    protected Boolean isActive;
    protected Boolean isResulted;
    protected PoolProvider poolProvider;
    protected List<SportsbookMarket> poolMarket;
    protected PoolType poolType;
    protected List<PoolResult> poolResult;

    /**
     * Gets the value of the poolKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoolKey() {
        return poolKey;
    }

    /**
     * Sets the value of the poolKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoolKey(String value) {
        this.poolKey = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link CurrencyCodeKind }
     *     
     */
    public CurrencyCodeKind getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrencyCodeKind }
     *     
     */
    public void setCurrency(CurrencyCodeKind value) {
        this.currency = value;
    }

    /**
     * Gets the value of the numLegs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumLegs() {
        return numLegs;
    }

    /**
     * Sets the value of the numLegs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumLegs(BigInteger value) {
        this.numLegs = value;
    }

    /**
     * Gets the value of the poolValue property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getPoolValue() {
        return poolValue;
    }

    /**
     * Sets the value of the poolValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setPoolValue(BigDecimal value) {
        this.poolValue = value;
    }

    /**
     * Gets the value of the isActive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsActive() {
        return isActive;
    }

    /**
     * Sets the value of the isActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsActive(Boolean value) {
        this.isActive = value;
    }

    /**
     * Gets the value of the isResulted property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsResulted() {
        return isResulted;
    }

    /**
     * Sets the value of the isResulted property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsResulted(Boolean value) {
        this.isResulted = value;
    }

    /**
     * Gets the value of the poolProvider property.
     * 
     * @return
     *     possible object is
     *     {@link PoolProvider }
     *     
     */
    public PoolProvider getPoolProvider() {
        return poolProvider;
    }

    /**
     * Sets the value of the poolProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoolProvider }
     *     
     */
    public void setPoolProvider(PoolProvider value) {
        this.poolProvider = value;
    }

    /**
     * Gets the value of the poolMarket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poolMarket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoolMarket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SportsbookMarket }
     * 
     * 
     */
    public List<SportsbookMarket> getPoolMarket() {
        if (poolMarket == null) {
            poolMarket = new ArrayList<SportsbookMarket>();
        }
        return this.poolMarket;
    }

    /**
     * Gets the value of the poolType property.
     * 
     * @return
     *     possible object is
     *     {@link PoolType }
     *     
     */
    public PoolType getPoolType() {
        return poolType;
    }

    /**
     * Sets the value of the poolType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PoolType }
     *     
     */
    public void setPoolType(PoolType value) {
        this.poolType = value;
    }

    /**
     * Gets the value of the poolResult property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the poolResult property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPoolResult().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PoolResult }
     * 
     * 
     */
    public List<PoolResult> getPoolResult() {
        if (poolResult == null) {
            poolResult = new ArrayList<PoolResult>();
        }
        return this.poolResult;
    }

}
