//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.product.sportsbook._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This class is a container for generic Category Characteristics to use for future extensibility
 * 
 * <p>Java class for SportsbookCategoryCharacteristics complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SportsbookCategoryCharacteristics"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hasCharacteristics" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="categoryCharacteristic" type="{http://cdm.ladbrokes.co.uk/product/Sportsbook/2.0}SportsbookCharacteristic" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SportsbookCategoryCharacteristics", propOrder = {
    "hasCharacteristics",
    "categoryCharacteristic"
})
public class SportsbookCategoryCharacteristics {

    protected Boolean hasCharacteristics;
    protected List<SportsbookCharacteristic> categoryCharacteristic;

    /**
     * Gets the value of the hasCharacteristics property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasCharacteristics() {
        return hasCharacteristics;
    }

    /**
     * Sets the value of the hasCharacteristics property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasCharacteristics(Boolean value) {
        this.hasCharacteristics = value;
    }

    /**
     * Gets the value of the categoryCharacteristic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the categoryCharacteristic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategoryCharacteristic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SportsbookCharacteristic }
     * 
     * 
     */
    public List<SportsbookCharacteristic> getCategoryCharacteristic() {
        if (categoryCharacteristic == null) {
            categoryCharacteristic = new ArrayList<SportsbookCharacteristic>();
        }
        return this.categoryCharacteristic;
    }

}
