//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.product.catalogue._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PriceRowTypeKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PriceRowTypeKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="SelectionPrice"/&gt;
 *     &lt;enumeration value="GamePlayPrice"/&gt;
 *     &lt;enumeration value="LottoLinePrice"/&gt;
 *     &lt;enumeration value="PokerBlindsPrice"/&gt;
 *     &lt;enumeration value="PokerBuyInPrice"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PriceRowTypeKind")
@XmlEnum
public enum PriceRowTypeKind {


    /**
     * A selection price type
     * 
     */
    @XmlEnumValue("SelectionPrice")
    SELECTION_PRICE("SelectionPrice"),

    /**
     * GamePlayPrice
     * 
     */
    @XmlEnumValue("GamePlayPrice")
    GAME_PLAY_PRICE("GamePlayPrice"),

    /**
     * GamePlayPrice
     * 
     */
    @XmlEnumValue("LottoLinePrice")
    LOTTO_LINE_PRICE("LottoLinePrice"),

    /**
     * Buy in cost for a Poker Cash Game (Big and Small Blinds)
     * 
     */
    @XmlEnumValue("PokerBlindsPrice")
    POKER_BLINDS_PRICE("PokerBlindsPrice"),

    /**
     * Buy in cost for a Poker Tournament (Single one off buy in)
     * 
     */
    @XmlEnumValue("PokerBuyInPrice")
    POKER_BUY_IN_PRICE("PokerBuyInPrice");
    private final String value;

    PriceRowTypeKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PriceRowTypeKind fromValue(String v) {
        for (PriceRowTypeKind c: PriceRowTypeKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
