//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.product.catalogue._2;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.common.channel._2.Channel;


/**
 * The catalogue entity represents a collection of 'domain' product categories and product offerings, available for customers to purchase/transact.
 * 
 * Example catalogues could be 'Online' and 'Mobile' (Sportsbook)
 * 
 * <p>Java class for ProductCatalogue complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductCatalogue"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="productCatalogueKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productCatalogueName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="productCatalogueState" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="channel" type="{http://cdm.ladbrokes.co.uk/common/Channel/2.0}Channel" minOccurs="0"/&gt;
 *         &lt;element name="category" type="{http://cdm.ladbrokes.co.uk/product/Catalogue/2.0}ProductCategory" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductCatalogue", propOrder = {
    "productCatalogueKey",
    "productCatalogueName",
    "productCatalogueState",
    "channel",
    "category"
})
public class ProductCatalogue {

    protected String productCatalogueKey;
    protected String productCatalogueName;
    protected String productCatalogueState;
    protected Channel channel;
    protected List<ProductCategory> category;

    /**
     * Gets the value of the productCatalogueKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCatalogueKey() {
        return productCatalogueKey;
    }

    /**
     * Sets the value of the productCatalogueKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCatalogueKey(String value) {
        this.productCatalogueKey = value;
    }

    /**
     * Gets the value of the productCatalogueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCatalogueName() {
        return productCatalogueName;
    }

    /**
     * Sets the value of the productCatalogueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCatalogueName(String value) {
        this.productCatalogueName = value;
    }

    /**
     * Gets the value of the productCatalogueState property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductCatalogueState() {
        return productCatalogueState;
    }

    /**
     * Sets the value of the productCatalogueState property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductCatalogueState(String value) {
        this.productCatalogueState = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link Channel }
     *     
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channel }
     *     
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the category property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCategory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductCategory }
     * 
     * 
     */
    public List<ProductCategory> getCategory() {
        if (category == null) {
            category = new ArrayList<ProductCategory>();
        }
        return this.category;
    }

}
