//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.product.catalogue._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubCategoryTypeKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SubCategoryTypeKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EventClass"/&gt;
 *     &lt;enumeration value="EventType"/&gt;
 *     &lt;enumeration value="EventSubtype"/&gt;
 *     &lt;enumeration value="Event"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SubCategoryTypeKind")
@XmlEnum
public enum SubCategoryTypeKind {


    /**
     * Subtype of SportsbookCategory
     * 
     */
    @XmlEnumValue("EventClass")
    EVENT_CLASS("EventClass"),

    /**
     * Subtype of SportsbookCategory
     * 
     */
    @XmlEnumValue("EventType")
    EVENT_TYPE("EventType"),

    /**
     * Subtype of SportsbookCategory
     * 
     */
    @XmlEnumValue("EventSubtype")
    EVENT_SUBTYPE("EventSubtype"),

    /**
     * Subtype of SportsbookCategory
     * 
     */
    @XmlEnumValue("Event")
    EVENT("Event");
    private final String value;

    SubCategoryTypeKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SubCategoryTypeKind fromValue(String v) {
        for (SubCategoryTypeKind c: SubCategoryTypeKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
