//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.betting.betslip._2;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.trading.selection._2.SelectionPrice;
import uk.co.ladbrokes.cdm.trading.selection._2.SelectionPriceType;


/**
 * This is the price that the Bet ws captured at.  This is not always directly related to a selection price, but if it is, then there is an association to the correct SelectionPrice.
 * 
 * The attribute may or may not be populated depending on the selectionpPriceType e.g. SP (Starting price) wont have a 'price' at point of capture, rather it will get the price at the start of the event, what ever that is.
 * 
 * <p>Java class for BetPrice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BetPrice"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numFractionalPrice" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="denFractionalPrice" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="americanPrice" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="decimalPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="selectionPriceType" type="{http://cdm.ladbrokes.co.uk/trading/Selection/2.0}SelectionPriceType" minOccurs="0"/&gt;
 *         &lt;element name="selectionPrice" type="{http://cdm.ladbrokes.co.uk/trading/Selection/2.0}SelectionPrice" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BetPrice", propOrder = {
    "numFractionalPrice",
    "denFractionalPrice",
    "americanPrice",
    "decimalPrice",
    "selectionPriceType",
    "selectionPrice"
})
public class BetPrice {

    protected BigInteger numFractionalPrice;
    protected BigInteger denFractionalPrice;
    protected BigInteger americanPrice;
    protected BigDecimal decimalPrice;
    protected SelectionPriceType selectionPriceType;
    protected SelectionPrice selectionPrice;

    /**
     * Gets the value of the numFractionalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumFractionalPrice() {
        return numFractionalPrice;
    }

    /**
     * Sets the value of the numFractionalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumFractionalPrice(BigInteger value) {
        this.numFractionalPrice = value;
    }

    /**
     * Gets the value of the denFractionalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDenFractionalPrice() {
        return denFractionalPrice;
    }

    /**
     * Sets the value of the denFractionalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDenFractionalPrice(BigInteger value) {
        this.denFractionalPrice = value;
    }

    /**
     * Gets the value of the americanPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAmericanPrice() {
        return americanPrice;
    }

    /**
     * Sets the value of the americanPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAmericanPrice(BigInteger value) {
        this.americanPrice = value;
    }

    /**
     * Gets the value of the decimalPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDecimalPrice() {
        return decimalPrice;
    }

    /**
     * Sets the value of the decimalPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDecimalPrice(BigDecimal value) {
        this.decimalPrice = value;
    }

    /**
     * Gets the value of the selectionPriceType property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionPriceType }
     *     
     */
    public SelectionPriceType getSelectionPriceType() {
        return selectionPriceType;
    }

    /**
     * Sets the value of the selectionPriceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionPriceType }
     *     
     */
    public void setSelectionPriceType(SelectionPriceType value) {
        this.selectionPriceType = value;
    }

    /**
     * Gets the value of the selectionPrice property.
     * 
     * @return
     *     possible object is
     *     {@link SelectionPrice }
     *     
     */
    public SelectionPrice getSelectionPrice() {
        return selectionPrice;
    }

    /**
     * Sets the value of the selectionPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectionPrice }
     *     
     */
    public void setSelectionPrice(SelectionPrice value) {
        this.selectionPrice = value;
    }

}
