//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.betting.betslip._2;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * This class represents the result information if a total Betslip has been resulted (i.e. the event is over, the result known). 
 * 
 * <p>Java class for BetslipResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BetslipResult"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="betslipResultCode" type="{http://cdm.ladbrokes.co.uk/betting/Betslip/2.0}BetslipResultKind" minOccurs="0"/&gt;
 *         &lt;element name="resultDateTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BetslipResult", propOrder = {
    "betslipResultCode",
    "resultDateTime"
})
public class BetslipResult {

    @XmlSchemaType(name = "string")
    protected BetslipResultKind betslipResultCode;
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar resultDateTime;

    /**
     * Gets the value of the betslipResultCode property.
     * 
     * @return
     *     possible object is
     *     {@link BetslipResultKind }
     *     
     */
    public BetslipResultKind getBetslipResultCode() {
        return betslipResultCode;
    }

    /**
     * Sets the value of the betslipResultCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BetslipResultKind }
     *     
     */
    public void setBetslipResultCode(BetslipResultKind value) {
        this.betslipResultCode = value;
    }

    /**
     * Gets the value of the resultDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getResultDateTime() {
        return resultDateTime;
    }

    /**
     * Sets the value of the resultDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setResultDateTime(XMLGregorianCalendar value) {
        this.resultDateTime = value;
    }

}
