//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.betting.betslip._2;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * This class represents Handicap detail of a selection
 * 
 * For Asian Handicap markets the handicap values will be a whole number which translates to a scale of single/twin offer. The sign (+/-) determines which team the handicap applies to. 
 * For straight handicap markets the handicap is the value which should be added/subtracted from the team scores. 
 * For over/under markets handicap contains the number of (goals, runs etc) that the over/under betting is on (typically 2.5 goals). 
 * For higher/lower markets handicap contains the pivot point for the higher/lower bets
 * 
 * <p>Java class for HandicapDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HandicapDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="handicapType" type="{http://cdm.ladbrokes.co.uk/betting/Betslip/2.0}BetHandicapTypeKind" minOccurs="0"/&gt;
 *         &lt;element name="handicapValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="handicapValue1" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="handicapValue2" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *         &lt;element name="handicapValue3" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HandicapDetail", propOrder = {
    "handicapType",
    "handicapValue",
    "handicapValue1",
    "handicapValue2",
    "handicapValue3"
})
public class HandicapDetail {

    @XmlSchemaType(name = "string")
    protected BetHandicapTypeKind handicapType;
    protected String handicapValue;
    protected BigDecimal handicapValue1;
    protected BigDecimal handicapValue2;
    protected BigDecimal handicapValue3;

    /**
     * Gets the value of the handicapType property.
     * 
     * @return
     *     possible object is
     *     {@link BetHandicapTypeKind }
     *     
     */
    public BetHandicapTypeKind getHandicapType() {
        return handicapType;
    }

    /**
     * Sets the value of the handicapType property.
     * 
     * @param value
     *     allowed object is
     *     {@link BetHandicapTypeKind }
     *     
     */
    public void setHandicapType(BetHandicapTypeKind value) {
        this.handicapType = value;
    }

    /**
     * Gets the value of the handicapValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHandicapValue() {
        return handicapValue;
    }

    /**
     * Sets the value of the handicapValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHandicapValue(String value) {
        this.handicapValue = value;
    }

    /**
     * Gets the value of the handicapValue1 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHandicapValue1() {
        return handicapValue1;
    }

    /**
     * Sets the value of the handicapValue1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHandicapValue1(BigDecimal value) {
        this.handicapValue1 = value;
    }

    /**
     * Gets the value of the handicapValue2 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHandicapValue2() {
        return handicapValue2;
    }

    /**
     * Sets the value of the handicapValue2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHandicapValue2(BigDecimal value) {
        this.handicapValue2 = value;
    }

    /**
     * Gets the value of the handicapValue3 property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getHandicapValue3() {
        return handicapValue3;
    }

    /**
     * Sets the value of the handicapValue3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setHandicapValue3(BigDecimal value) {
        this.handicapValue3 = value;
    }

}
