//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.betting.betslip._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * This class contains line summary information as a result of settlement
 * 
 * <p>Java class for SettlementLineSummary complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SettlementLineSummary"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numSelections" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="numLegs" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="numLines" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="numVoidLines" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="numWinLines" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="numLoseLines" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SettlementLineSummary", propOrder = {
    "numSelections",
    "numLegs",
    "numLines",
    "numVoidLines",
    "numWinLines",
    "numLoseLines"
})
public class SettlementLineSummary {

    protected BigInteger numSelections;
    protected BigInteger numLegs;
    protected BigInteger numLines;
    protected BigInteger numVoidLines;
    protected BigInteger numWinLines;
    protected BigInteger numLoseLines;

    /**
     * Gets the value of the numSelections property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumSelections() {
        return numSelections;
    }

    /**
     * Sets the value of the numSelections property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumSelections(BigInteger value) {
        this.numSelections = value;
    }

    /**
     * Gets the value of the numLegs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumLegs() {
        return numLegs;
    }

    /**
     * Sets the value of the numLegs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumLegs(BigInteger value) {
        this.numLegs = value;
    }

    /**
     * Gets the value of the numLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumLines() {
        return numLines;
    }

    /**
     * Sets the value of the numLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumLines(BigInteger value) {
        this.numLines = value;
    }

    /**
     * Gets the value of the numVoidLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumVoidLines() {
        return numVoidLines;
    }

    /**
     * Sets the value of the numVoidLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumVoidLines(BigInteger value) {
        this.numVoidLines = value;
    }

    /**
     * Gets the value of the numWinLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumWinLines() {
        return numWinLines;
    }

    /**
     * Sets the value of the numWinLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumWinLines(BigInteger value) {
        this.numWinLines = value;
    }

    /**
     * Gets the value of the numLoseLines property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumLoseLines() {
        return numLoseLines;
    }

    /**
     * Sets the value of the numLoseLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumLoseLines(BigInteger value) {
        this.numLoseLines = value;
    }

}
