//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.event._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.common.characteristic._2.Characteristic;


/**
 * Maintains the characteristics for the event type
 * 
 * <p>Java class for EventTypeCharacteristic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventTypeCharacteristic"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cdm.ladbrokes.co.uk/common/Characteristic/2.0}Characteristic"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="eventTypeCharacteristicId" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventTypeCharacteristic", propOrder = {
    "eventTypeCharacteristicId"
})
public class EventTypeCharacteristic
    extends Characteristic
{

    protected BigInteger eventTypeCharacteristicId;

    /**
     * Gets the value of the eventTypeCharacteristicId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEventTypeCharacteristicId() {
        return eventTypeCharacteristicId;
    }

    /**
     * Sets the value of the eventTypeCharacteristicId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEventTypeCharacteristicId(BigInteger value) {
        this.eventTypeCharacteristicId = value;
    }

}
