//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.event._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.common.channel._2.Channel;


/**
 * Maintains the channels for the event sub type.
 * 
 * <p>Java class for EventSubtypeChannel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventSubtypeChannel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="deleteFlag" type="{http://cdm.ladbrokes.co.uk/trading/Event/2.0}DeleteFlagKind" minOccurs="0"/&gt;
 *         &lt;element name="eventSubtypeChannelId" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="channel" type="{http://cdm.ladbrokes.co.uk/common/Channel/2.0}Channel" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventSubtypeChannel", propOrder = {
    "deleteFlag",
    "eventSubtypeChannelId",
    "channel"
})
public class EventSubtypeChannel {

    @XmlSchemaType(name = "string")
    protected DeleteFlagKind deleteFlag;
    protected BigInteger eventSubtypeChannelId;
    protected Channel channel;

    /**
     * Gets the value of the deleteFlag property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteFlagKind }
     *     
     */
    public DeleteFlagKind getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * Sets the value of the deleteFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteFlagKind }
     *     
     */
    public void setDeleteFlag(DeleteFlagKind value) {
        this.deleteFlag = value;
    }

    /**
     * Gets the value of the eventSubtypeChannelId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getEventSubtypeChannelId() {
        return eventSubtypeChannelId;
    }

    /**
     * Sets the value of the eventSubtypeChannelId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setEventSubtypeChannelId(BigInteger value) {
        this.eventSubtypeChannelId = value;
    }

    /**
     * Gets the value of the channel property.
     * 
     * @return
     *     possible object is
     *     {@link Channel }
     *     
     */
    public Channel getChannel() {
        return channel;
    }

    /**
     * Sets the value of the channel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Channel }
     *     
     */
    public void setChannel(Channel value) {
        this.channel = value;
    }

}
