//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.event._2;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import uk.co.ladbrokes.cdm.trading.participant._2.Participant;


/**
 * Maintains participant details for events.
 * 
 * <p>Java class for EventParticipant complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventParticipant"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="participantNo" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="deleteFlag" type="{http://cdm.ladbrokes.co.uk/trading/Event/2.0}DeleteFlagKind" minOccurs="0"/&gt;
 *         &lt;element name="eventKey" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="participant" type="{http://cdm.ladbrokes.co.uk/trading/Participant/2.0}Participant" minOccurs="0"/&gt;
 *         &lt;element name="duration" type="{http://cdm.ladbrokes.co.uk/trading/Event/2.0}EventParticipantDuration" minOccurs="0"/&gt;
 *         &lt;element name="characteristic" type="{http://cdm.ladbrokes.co.uk/trading/Event/2.0}EventParticipantCharacteristic" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventParticipant", propOrder = {
    "participantNo",
    "deleteFlag",
    "eventKey",
    "participant",
    "duration",
    "characteristic"
})
public class EventParticipant {

    protected BigInteger participantNo;
    @XmlSchemaType(name = "string")
    protected DeleteFlagKind deleteFlag;
    protected String eventKey;
    protected Participant participant;
    protected EventParticipantDuration duration;
    protected List<EventParticipantCharacteristic> characteristic;

    /**
     * Gets the value of the participantNo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getParticipantNo() {
        return participantNo;
    }

    /**
     * Sets the value of the participantNo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setParticipantNo(BigInteger value) {
        this.participantNo = value;
    }

    /**
     * Gets the value of the deleteFlag property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteFlagKind }
     *     
     */
    public DeleteFlagKind getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * Sets the value of the deleteFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteFlagKind }
     *     
     */
    public void setDeleteFlag(DeleteFlagKind value) {
        this.deleteFlag = value;
    }

    /**
     * Gets the value of the eventKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEventKey() {
        return eventKey;
    }

    /**
     * Sets the value of the eventKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEventKey(String value) {
        this.eventKey = value;
    }

    /**
     * Gets the value of the participant property.
     * 
     * @return
     *     possible object is
     *     {@link Participant }
     *     
     */
    public Participant getParticipant() {
        return participant;
    }

    /**
     * Sets the value of the participant property.
     * 
     * @param value
     *     allowed object is
     *     {@link Participant }
     *     
     */
    public void setParticipant(Participant value) {
        this.participant = value;
    }

    /**
     * Gets the value of the duration property.
     * 
     * @return
     *     possible object is
     *     {@link EventParticipantDuration }
     *     
     */
    public EventParticipantDuration getDuration() {
        return duration;
    }

    /**
     * Sets the value of the duration property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventParticipantDuration }
     *     
     */
    public void setDuration(EventParticipantDuration value) {
        this.duration = value;
    }

    /**
     * Gets the value of the characteristic property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characteristic property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacteristic().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EventParticipantCharacteristic }
     * 
     * 
     */
    public List<EventParticipantCharacteristic> getCharacteristic() {
        if (characteristic == null) {
            characteristic = new ArrayList<EventParticipantCharacteristic>();
        }
        return this.characteristic;
    }

}
