//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.event._2;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchStateKind.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MatchStateKind"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EndOfMatch"/&gt;
 *     &lt;enumeration value="MatchRetirement"/&gt;
 *     &lt;enumeration value="MatchWalkover"/&gt;
 *     &lt;enumeration value="MatchDefaulted"/&gt;
 *     &lt;enumeration value="MatchAbandoned"/&gt;
 *     &lt;enumeration value="NormalFinish"/&gt;
 *     &lt;enumeration value="GameCanceled"/&gt;
 *     &lt;enumeration value="GameSuspended"/&gt;
 *     &lt;enumeration value="GamePostponedByMoreThan36Hours"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MatchStateKind")
@XmlEnum
public enum MatchStateKind {

    @XmlEnumValue("EndOfMatch")
    END_OF_MATCH("EndOfMatch"),
    @XmlEnumValue("MatchRetirement")
    MATCH_RETIREMENT("MatchRetirement"),
    @XmlEnumValue("MatchWalkover")
    MATCH_WALKOVER("MatchWalkover"),
    @XmlEnumValue("MatchDefaulted")
    MATCH_DEFAULTED("MatchDefaulted"),
    @XmlEnumValue("MatchAbandoned")
    MATCH_ABANDONED("MatchAbandoned"),
    @XmlEnumValue("NormalFinish")
    NORMAL_FINISH("NormalFinish"),
    @XmlEnumValue("GameCanceled")
    GAME_CANCELED("GameCanceled"),
    @XmlEnumValue("GameSuspended")
    GAME_SUSPENDED("GameSuspended"),
    @XmlEnumValue("GamePostponedByMoreThan36Hours")
    GAME_POSTPONED_BY_MORE_THAN_36_HOURS("GamePostponedByMoreThan36Hours");
    private final String value;

    MatchStateKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MatchStateKind fromValue(String v) {
        for (MatchStateKind c: MatchStateKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
