//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.event._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Round complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Round"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="roundId" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="roundName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="abelsonName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Round", propOrder = {
    "roundId",
    "roundName",
    "abelsonName"
})
public class Round {

    protected BigInteger roundId;
    protected String roundName;
    protected String abelsonName;

    /**
     * Gets the value of the roundId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getRoundId() {
        return roundId;
    }

    /**
     * Sets the value of the roundId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setRoundId(BigInteger value) {
        this.roundId = value;
    }

    /**
     * Gets the value of the roundName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoundName() {
        return roundName;
    }

    /**
     * Sets the value of the roundName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoundName(String value) {
        this.roundName = value;
    }

    /**
     * Gets the value of the abelsonName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbelsonName() {
        return abelsonName;
    }

    /**
     * Sets the value of the abelsonName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbelsonName(String value) {
        this.abelsonName = value;
    }

}
