//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.event._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SessionDetails complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SessionDetails"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numSessions" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="sessionDetail" type="{http://cdm.ladbrokes.co.uk/trading/Event/2.0}SessionDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SessionDetails", propOrder = {
    "numSessions",
    "sessionDetail"
})
public class SessionDetails {

    protected BigInteger numSessions;
    protected SessionDetail sessionDetail;

    /**
     * Gets the value of the numSessions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumSessions() {
        return numSessions;
    }

    /**
     * Sets the value of the numSessions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumSessions(BigInteger value) {
        this.numSessions = value;
    }

    /**
     * Gets the value of the sessionDetail property.
     * 
     * @return
     *     possible object is
     *     {@link SessionDetail }
     *     
     */
    public SessionDetail getSessionDetail() {
        return sessionDetail;
    }

    /**
     * Sets the value of the sessionDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link SessionDetail }
     *     
     */
    public void setSessionDetail(SessionDetail value) {
        this.sessionDetail = value;
    }

}
