//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.28 at 12:39:51 PM IST 
//


package uk.co.ladbrokes.cdm.trading.event._2;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TennisDynamicData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TennisDynamicData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="noWinningSets" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="gameChanged" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="setChanged" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="aceChanged" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="doubleFaultChanged" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="pointChanged" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="totalAces" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *         &lt;element name="totalDF" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TennisDynamicData", propOrder = {
    "noWinningSets",
    "gameChanged",
    "setChanged",
    "aceChanged",
    "doubleFaultChanged",
    "pointChanged",
    "totalAces",
    "totalDF"
})
public class TennisDynamicData {

    protected BigInteger noWinningSets;
    protected Boolean gameChanged;
    protected Boolean setChanged;
    protected Boolean aceChanged;
    protected Boolean doubleFaultChanged;
    protected Boolean pointChanged;
    protected BigInteger totalAces;
    protected BigInteger totalDF;

    /**
     * Gets the value of the noWinningSets property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNoWinningSets() {
        return noWinningSets;
    }

    /**
     * Sets the value of the noWinningSets property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNoWinningSets(BigInteger value) {
        this.noWinningSets = value;
    }

    /**
     * Gets the value of the gameChanged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isGameChanged() {
        return gameChanged;
    }

    /**
     * Sets the value of the gameChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setGameChanged(Boolean value) {
        this.gameChanged = value;
    }

    /**
     * Gets the value of the setChanged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSetChanged() {
        return setChanged;
    }

    /**
     * Sets the value of the setChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSetChanged(Boolean value) {
        this.setChanged = value;
    }

    /**
     * Gets the value of the aceChanged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAceChanged() {
        return aceChanged;
    }

    /**
     * Sets the value of the aceChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAceChanged(Boolean value) {
        this.aceChanged = value;
    }

    /**
     * Gets the value of the doubleFaultChanged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDoubleFaultChanged() {
        return doubleFaultChanged;
    }

    /**
     * Sets the value of the doubleFaultChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDoubleFaultChanged(Boolean value) {
        this.doubleFaultChanged = value;
    }

    /**
     * Gets the value of the pointChanged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isPointChanged() {
        return pointChanged;
    }

    /**
     * Sets the value of the pointChanged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setPointChanged(Boolean value) {
        this.pointChanged = value;
    }

    /**
     * Gets the value of the totalAces property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalAces() {
        return totalAces;
    }

    /**
     * Sets the value of the totalAces property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalAces(BigInteger value) {
        this.totalAces = value;
    }

    /**
     * Gets the value of the totalDF property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalDF() {
        return totalDF;
    }

    /**
     * Sets the value of the totalDF property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalDF(BigInteger value) {
        this.totalDF = value;
    }

}
